var gapLv1 = 100;
var gapLv2 = 150;
var gapLv3 = 200;
var gapLv4 = 300;
var gapLv5 = 400;
var poleMaxHeight = 380;
var poleMinHeight = 250;
var heightLv1 = 420;
var heightLv2 = 350;
var heightLv3 = 250;
var heightLv4 = 230;
var maxPoleGap;
var minPoleGap;
var easy = document.getElementById('easy');
var start = document.getElementById('start');
var medium = document.getElementById('medium');
var difficult = document.getElementById('difficult');
var ballPower = 60;
var ballGravity = 100;
var gameover = document.getElementById("gameover"); 
var repEasy = document.getElementById('repEasy');
var repMedium = document.getElementById('repMedium');
var repDifficult = document.getElementById('repDifficult');
var showScore = document.getElementById('score');
var showTopScore = document.getElementById('topScore');
var ninjaGravity = 750;